settings:
  prediction-threshold: 0.6  
  name: 'ViT-H/14'
  device: 'cuda'

label-settings:
  labels:
    # - 'people fighting'
    # - 'violence'
    # - 'person attacking'
    # - 'person threatening'
    # - 'suspicious behavior'
    # - 'people running in panic'
    # - 'person with weapon'
    # - 'aggressive group behavior'
    # - 'people screaming'
    # - 'dangerous situation'
    # - 'unusual crowd movement'
    - 'violence'

  default-label: 'normal behavior'
